CREATE VIEW VWUSUARIOS (
    ID, NOME, NASCIMENTO, EMAIL
) AS 
    SELECT 
    ID, NOME, NASCIMENTO, EMAIL
    FROM
    CLIENTES
    UNION
    SELECT 
    ID, NOME, NASCIMENTO, EMAIL
    FROM
    FUNCIONARIOS;